export {default as IcoAdvantChat} from './advant-chat.svg'
export {default as IcoAdvantHomework} from './advant-homework.svg'
export {default as IcoAdvantTask} from './advant-task.svg'
export {default as IcoAdvantVideo} from './advant-video.svg'
export {default as IcoFreeLesson} from './free.svg'
export {default as IcoTelegram} from './telegramm.svg'
export {default as IcoViber} from './viber-iconk.svg'
export {default as IcoGroup1} from './Group (4).svg'
export {default as IcoGroup2} from './Group (2).svg'
export {default as IcoGroup3} from './Group (3).svg'
export {default as IcoSmile} from './smile.svg'
export {default as IcoCircle} from './circle.svg'
